resources:
  - url: http://127.0.0.1:6000/minimalistic-area-card.js
    type: module
views:
  - cards:
      - type: custom:minimalistic-area-card
        title: 'Kitchen'
        image: 'https://demo.home-assistant.io/stub_config/kitchen.png'
        tap_action:
          action: navigate
          navigation_path: /test
        entities:
          - entity: sun.sun
