name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'yarn'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build and test
        run: yarn build

      # Upload build file to the release as an asset.
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'dist/better-minimalistic-area-card.js'
          asset_name: better-minimalistic-area-card.js
          tag: ${{ github.ref }}
          overwrite: true
